### ISSUE TITLE
Add an option to navigate back to correct the labels

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/supervising-ui#4]

**Comment by linnabraham** [comment]
Is there a solution for this?

**Comment by thammegowda** [comment]
yes, please use the "back to previous page" option of your web browser :)

**Comment by linnabraham** [comment]
ya. Thats clever! But that is a possibility only if we are on the same session. Once the session has ended how can we come back and change some of the labels.

**Comment by thammegowda** [comment]
@linnabraham 
Once the session is gone, there is no concept of "back" unless we reinitialize the same session.
So, what you are looking for is relabeling all of them?
Well this issue is still open (assume relabelling by second user) https://github.com/USCDataScience/supervising-ui/issues/5 

perhaps you could spin up another instance and relabel, and merge the results manually where the labels mismatch.

(Since I am not working on this project anymore, and not my top of the list)
If this is a necessary feature for you, you are welcome to look inside this https://github.com/USCDataScience/supervising-ui/blob/master/app.py 
and send a pull request.

Cheers,
